config/routes.rb
Invinyx::Application.routes.draw do
  get "obra/index"

  get "proveedors/index"

  get "factura/index"

  resources :productos
  resources :pedidos do
    resources :devolucions, only: [:new]
    member do
      get :devoluciones
    end
  end
  resources :articulos
  resources :facturas
  resources :proveedors
  resources :devolucions
  resources :obras

  get "/agregar/empleado/:id" => 'pedidos#asignar_empleado_a_pedido', :as => :empleado_info 

  get "/agregar/articulo/:id" => 'pedidos#asignar_articulo_a_pedido', :as => :articulo_info
  
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users

  get '/agregar/:id' => 'application#articulos_facturas',  :as => :articulos_facturas

  

  root :to => 'articulos#index'

  match ':controller(/:action(/:id))(.:format)'
end

app/models/pedido.rb
class Pedido < ActiveRecord::Base
  attr_accessible :empleado_id, :obra_id, :lista_de_articulos_attributes
  has_many :lista_de_articulos, :class_name => "PedidoHasArticulo"
  has_many :articulos, :through => :lista_de_articulos
  belongs_to :obra
  belongs_to :empleado
  accepts_nested_attributes_for :lista_de_articulos, :allow_destroy => true
  before_save :asignar_estado_individual, :asignar_estado_general
  before_create :restar_cantidad_a_articulo
  validates_presence_of :empleado_id, :obra_id
  validates_presence_of :lista_de_articulos, message: I18n.t('errors.messages.lista_de_articulos')
  validate :cantidad_de_pedido_mayor?


  #valida cuando la cantidad del articulo pedido es mayor a la cantidad del articulo
  def cantidad_de_pedido_mayor?
    self.lista_de_articulos.each  do |registro|
      articulo = Articulo.find(registro.articulo_id)
      if registro.cantidad && registro.cantidad > articulo.cantidad
        return errors.add(:lista_de_articulos, "EL articulo #{articulo.codigo} la cantidad pedida excede a la del inventario")
      end
    end
    false
  end

  def asignar_estado_general
    self.lista_de_articulos.each do |registro|
      if registro.estado == "Activo"
        self.estado = "Activo"
        break
      elsif 
        self.estado = "Retribuido"
      end
    end
  end

  def asignar_estado_individual
    self.lista_de_articulos.each do |registro|
      articulo = Articulo.find(registro.articulo_id)
      if articulo.consumible
        registro.estado = "Consumible"
      elsif !articulo.consumible && registro.cantidad_devuelta == registro.cantidad
        registro.estado = "Retribuido"
      else
        registro.estado = "Activo" 
      end
    end
  end

  #retorna la cantidad devuelta de cada articulo pedido
  def cantidad_devuelta_del_articulo_pedido(articulo)
    pedido = PedidoHasArticulo.where(pedido_id: self.id, articulo_id: articulo)
    pedido.first.cantidad_devuelta
  end

  #retorna la cantidad que falta por devolver del pedido
  def cantidad_por_remunerar(articulo)
    self.cantidad_del_articulo_pedido(articulo)-self.cantidad_devuelta_del_articulo_pedido(articulo)
  end

  #retorna el estado de cada articulo pedido
  def estado_del_articulo_pedido(articulo)
    pedido = PedidoHasArticulo.where(pedido_id: self.id, articulo_id: articulo)
    pedido.first.estado
  end

	#retorna la cantidad que se pidio por cada articulo
  def cantidad_del_articulo_pedido(articulo)
		pedido = PedidoHasArticulo.where(pedido_id: self.id, articulo_id: articulo)
		pedido.first.cantidad
	end

  #resta la cantidad pedida al articulo
  def restar_cantidad_a_articulo
    self.lista_de_articulos.each do |registro|
      articulo = Articulo.find(registro.articulo_id)
      articulo.update_attribute(:cantidad, articulo.cantidad-registro.cantidad)
    end 
  end

  #retorna un array con todas las devoluciones de un pedido
  def obtener_devoluciones_individuales
    DevolucionHasPedidoshasarticulo.where(pedido_has_articulo_id: self.id)
  end

  def obtener_devoluciones_generales
    @devolucion_ids = []
    self.obtener_devoluciones_individuales.each do |devolucion|
      @devolucion_ids << devolucion.devolucion_id
    end
    @devolucion_ids.uniq.map { |id| Devolucion.find(id) }
  end
  
  rails_admin do 
  	field :empleado
  end

  def self.listado_de_articulos_por_obra(obra)
    @listado = []
    Pedido.cantidad_de_articulos_por_obra(obra.id).each_pair do |k,v| 
      @listado << [Articulo.find(k), v]
    end
    @listado
  end

  private

  def self.cantidad_de_articulos_por_obra(id)
    @articulos = {}
    Pedido.where(obra_id: id).each do |pedido|
      pedido.lista_de_articulos.each do |articulos|
        if @articulos.include?(articulos.articulo_id) 
          @articulos[articulos.articulo_id]+=articulos.cantidad
        else
          @articulos.merge!(articulos.articulo_id => articulos.cantidad)
        end
      end 
    end
    @articulos      
  end

end

app/controllers/pedidos_controller.rb
class PedidosController < ApplicationController
  
  before_filter :authenticate_user!


  def index
  	@pedidos = Pedido.all
  end

  def show
  	@pedido = Pedido.find(params[:id])
  end

  def new
    @pedido = Pedido.new
  	@empleados = Empleado.all
  	@articulos = Articulo.all
  end

  def create
    @pedido = Pedido.new(params[:pedido])
    @empleados = Empleado.all
    respond_to do |format|
      if @pedido.save
        format.html { redirect_to @pedido, notice: 'Producto was successfully created.' }
      else
        format.html { render action: "new" }
        format.json { render json: @pedido.errors, status: :unprocessable_entity }
      end
    end
  end

  def devoluciones
    @pedido = Pedido.find(params[:id])
  end

  def asignar_empleado_a_pedido  	
  	@empleado = Empleado.find(params[:id])
  end

  def asignar_articulo_a_pedido   
    @articulo = Articulo.find(params[:id])
  end

end

app/helpers/pedidos_helper.rb
module PedidosHelper
end

app/views/pedidos/_agregar_articulo.html.haml
%tr{id:"#{articulo.id}"}
	%td#id-pedido
		=text_field_tag "pedido[lista_de_articulos_attributes][#{articulo.id}][articulo_id]", "#{articulo.id}", id:'input_codigo', readonly:'readonly'
	%td 
		=articulo.codigo
	%td
		=articulo.nombre
	%td
		=text_field_tag "pedido[lista_de_articulos_attributes][#{articulo.id}][cantidad]", "0", id:'input_cantidad'
		=articulo.unidad_de_medida
	%td
		=link_to_function '<i class="icon-remove"></i>'.html_safe, "remover('#{articulo.id}')", class: "btn btn-danger", remote: true

:javascript
	function remover(id){
		$('.agregar #'+id).remove()
		if($('.agregar tr').size()==0){
			$('.agregar').append("<tr id='anuncio'><td colspan='4'><center>No hay articulos en la lista</center></td></tr>");
		}
	}

app/views/pedidos/_form.html.haml
= form_for(@pedido) do |f|
	- if @pedido.errors.any?
		%br
		.alert.alert-error#error_explanation
			=link_to_function "x", "alert('close')" , class: "close", data_dismiss: "alert" 
			%h2 
				No se ha podido guardar el producto, verifique los siguientes errores.
			%ul
			- @pedido.errors.full_messages.each do |msg|
				%li= msg

= form_for @pedido do |f|
	.row.row-invinyx 
		%br
		.span12
			= f.hidden_field :empleado_id, id: "idEmpleado"
			.span3
				= f.label :cedula

				= text_field_tag :cedula, "", class: "span3 uneditable-input", id: "cedulaEmpleado", readonly: "readonly", type:"", tittle: "Cédula"			
			.span3

				= f.label :nombre

				= text_field_tag "Nombre","", class: "span3 uneditable-input", id: "nombreEmpleado", readonly: "readonly", type:""
			.span3
				= f.label :apellido

				= text_field_tag "Apellido","", class: "span3 uneditable-input", id: "apellidoEmpleado", readonly: "readonly", type:""	
				
			.span2
				%br
				=link_to '<i class="icon-search"></i>'.html_safe, "#EmpleadosModal", class: "btn btn-large btn-info", id: "buscarEmpleado", "data-toggle" => "modal", role: "button", title:"Buscar Empeado"
				%br
		.span12
			.span3
				%br
				= f.label :telefono

				= text_field_tag "Telefono","", class: "span3 uneditable-input", id: "telefonoEmpleado", readonly: "readonly", type:""
				
			.span3
				%br
				= f.label :cargo

				= text_field_tag "Cargo","", class: "span3 uneditable-input", id: "cargoEmpleado", readonly: "readonly", type:""				
				%br
			.span3
				%br
				= f.label :obra_id

				= f.collection_select(:obra_id, Obra.all(:order => 'nombre'), :id, :nombre, { :prompt => 'Selecionar Obra' }, class: "span3" )
	%br
	%hr	

	.page-header
		%center
			%h4
				Lista de Articulos
	%br
	%br
	.row.row-invinyx
		.span6
			%table.table.table-bordered.tablaEstandar
				%thead
					%tr
						%th Codigo
						%th Nombre
						%th Cantidad
						%th Acciones
				%tbody
					- @articulos.each do |articulo|
						- if articulo.cantidad > 0
							%tr
								%td
									=articulo.codigo
								%td 
									=articulo.nombre
								- if articulo.advertencia_stock == 1
									%th{:style=>"background: #82FA58;"}
										=articulo.cantidad
										=articulo.unidad_de_medida
								- elsif articulo.advertencia_stock == 2
									%th{:style=>"background: #FA5858;"}
										=articulo.cantidad
										=articulo.unidad_de_medida
								- else
									%th{:style=>"background: #F4FA58;"}
										=articulo.cantidad
										=articulo.unidad_de_medida
								%td
									=link_to_function '<i class="icon-plus"></i>'.html_safe, "agregar('#{articulo.id}', '/agregar/articulo/')", class: "btn btn-success", remote: true
		.span6
			%table.table.table-bordered#articulosAgregado
				%thead
					%tr
						%th#id-pedido
						%th Codigo
						%th Nombre
						%th Cantidad
						%th Acciones
				%tbody.agregar
					%tr#anuncio
						%th{ :colspan=>"4" }
							%center
								No hay articulos en la lista
	%br
	%br
	.modal-footer	
		= f.submit class: "btn btn-primary"
		=link_to"Volver", pedidos_path, class: "btn"

:javascript
	function alert(accion) {
		$(".alert").alert(accion)
	}

app/views/pedidos/asignar_articulo_a_pedido.js.erb
$("#articulosAgregado .agregar").append("<%= escape_javascript(render partial: 'pedidos/agregar_articulo', locals: { articulo: @articulo } ) %>")

app/views/pedidos/asignar_empleado_a_pedido.js.erb
$("#EmpleadosModal").modal("hide");
$("#idEmpleado").val("<%= @empleado.id %>")
$("#cedulaEmpleado").val("<%= @empleado.cedula %>")
$("#nombreEmpleado").val("<%= @empleado.nombre %>")
$("#apellidoEmpleado").val("<%= @empleado.apellido %>")
$("#cargoEmpleado").val("<%= @empleado.cargo %>")
$("#telefonoEmpleado").val("<%= @empleado.telefono %>")
$("#obraEmpleado").val("<%= @empleado.obra.nombre %>")

app/views/pedidos/devoluciones.html.haml
.hero-unit	
	%h2
		%center
			%i.icon-random
			="Devoluciones del Pedido ##{@pedido.id}"
%br 
%table.table.table-bordered.articulos
	%thead
		%tr
			%th #
			%th Descripción
			%th Fecha de realización
			%th Acciones
	%tbody
		- @pedido.obtener_devoluciones_generales.each do |devolucion|
			%tr
				%td 
					=devolucion.id
				%td 
					=devolucion.descripcion
				%td
					=devolucion.created_at.strftime("%Y-%m-%d")
				%td
					=link_to '<i class="icon-info-sign"></i>'.html_safe, devolucion, :class=>"btn btn-info", title: "Ver Detalles"
					
:javascript
	(function() {
		jQuery(function() {
			return $('.articulos').dataTable({
				"oLanguage": {
					"sProcessing": "Procesando...",
					"sLengthMenu": "Mostrar _MENU_ registros",
					"sZeroRecords": "No se encontraron resultados",
					"sEmptyTable": "Ningún dato disponible en esta tabla",
					"sInfo": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
					"sInfoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros",
					"sInfoFiltered": "(filtrado de un total de _MAX_ registros)",
					"sInfoPostFix": "",
					"sSearch": "<i class='icon-search'></i>",
					"sUrl": "",
					"sInfoThousands": ",",
					"sLoadingRecords": "Cargando...",
					"oPaginate": {
						"sFirst": "Primero",
						"sLast": "Último",
						"sNext": "Siguiente",
						"sPrevious": "Anterior"
					},
					"oAria": {
						"sSortAscending": ": Activar para ordenar la columna de manera ascendente",
						"sSortDescending": ": Activar para ordenar la columna de manera descendente"
					}
				},
				"sDom": "<'row-fluid'<'span6'l><'span6'f>r>t<'row-fluid'<'span6'i><'span6'p>>",
				"sPaginationType": "bootstrap",
				"aaSorting": [[ 0, "desc" ]]
			});
		});
	}).call(this);

app/views/pedidos/index.html.haml
- content_for :title, "Lista de Pedidos"
.hero-unit	
	%h2
		%center
			%i.icon-shopping-cart
			Lista de Pedidos
.well	
	%p
		= link_to '<i class="icon-plus"> Nuevo Pedido</i>'.html_safe, new_pedido_path, class: "btn btn-success"	
%br 
%table.table.table-bordered.articulos
	%thead
		%tr
			%th #
			%th C.I
			%th Empleado
			%th Obra
			%th Estado
			%th Fecha
			%th Acciones
	%tbody
		- @pedidos.each do |pedido|
			%tr
				%td 
					=pedido.id
				%td 
					=pedido.empleado.cedula
				%th
					=pedido.empleado.nombre
					=pedido.empleado.apellido
				%th
					=pedido.obra.nombre
				- if pedido.estado == "Activo"
					%th{:style=>"background: #82FA58;"}
						=pedido.estado
				- else
					%th{:style=>"background: #FA5858;"}
						=pedido.estado
				%th
					=pedido.created_at.strftime("%Y-%m-%d")
				%td
					=link_to '<i class="icon-info-sign"></i>'.html_safe, pedido, :class=>"btn btn-info", title: "Ver Detalles"
					=link_to '<i class="icon-random"></i>'.html_safe, new_pedido_devolucion_path(pedido), :class=>"btn", :title=>"Realizar Devolución"
					=link_to '<i class=" icon-eye-open"></i>'.html_safe, devoluciones_pedido_path(pedido.id), :class=>"btn", :title=>"Ver Devoluciones", :'data-skip-pjax' => false

					
					
:javascript
	(function() {
		jQuery(function() {
			return $('.articulos').dataTable({
				"oLanguage": {
					"sProcessing": "Procesando...",
					"sLengthMenu": "Mostrar _MENU_ registros",
					"sZeroRecords": "No se encontraron resultados",
					"sEmptyTable": "Ningún dato disponible en esta tabla",
					"sInfo": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
					"sInfoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros",
					"sInfoFiltered": "(filtrado de un total de _MAX_ registros)",
					"sInfoPostFix": "",
					"sSearch": "<i class='icon-search'></i>",
					"sUrl": "",
					"sInfoThousands": ",",
					"sLoadingRecords": "Cargando...",
					"oPaginate": {
						"sFirst": "Primero",
						"sLast": "Último",
						"sNext": "Siguiente",
						"sPrevious": "Anterior"
					},
					"oAria": {
						"sSortAscending": ": Activar para ordenar la columna de manera ascendente",
						"sSortDescending": ": Activar para ordenar la columna de manera descendente"
					}
				},
				"sDom": "<'row-fluid'<'span6'l><'span6'f>r>t<'row-fluid'<'span6'i><'span6'p>>",
				"sPaginationType": "bootstrap",
				"aaSorting": [[ 0, "desc" ]]
			});
		});
	}).call(this);

app/views/pedidos/new.html.haml
.hero-unit	
	%h2
		%center
			%i.icon-shopping-cart
			Nuevo Pedido
%hr
.page-header
	%center
		%h4 Datos del Empleado

= render 'form'


#EmpleadosModal.modal.hide.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
	.modal-header
		%button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} ×
		%h3#myModalLabel Buscar Empleado
	.modal-body
		%table.table.table-bordered.tablaEstandar
			%thead
				%tr
					%th C.I
					%th Nombre
					%th Apellido
					%th Cargo
					%th Control
			%tbody
				- @empleados.each do |empleado|
					%tr
						%td
							=empleado.cedula
						%td 
							=empleado.nombre
						%td 
							=empleado.apellido
						%td 
							=empleado.cargo
						%td
							=link_to_function '<i class="icon-plus"></i>'.html_safe, "agregar('#{empleado.id}', '/agregar/empleado/')", class: "btn btn-success", remote: true
	.modal-footer

:javascript

	function agregar(id, ruta) {
		$('#anuncio').remove()
		if($("#"+id).size()==0){			
			$.get(ruta+id)
		} else { alert("Este artículo ya ha sido agregado a la lista.") }
	}	

	$('.tablaEstandar').dataTable({
		"oLanguage": {
			"sProcessing": "Procesando...",
			"sLengthMenu": "Mostrar _MENU_ registros",
			"sZeroRecords": "No se encontraron resultados",
			"sEmptyTable": "Ningún dato disponible en esta tabla",
			"sInfo": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
			"sInfoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros",
			"sInfoFiltered": "(filtrado de un total de _MAX_ registros)",
			"sInfoPostFix": "",
			"sSearch": "<i class='icon-search'></i>",
			"sUrl": "",
			"sInfoThousands": ",",
			"sLoadingRecords": "Cargando...",
			"oPaginate": {
				"sFirst": "Primero",
				"sLast": "Último",
				"sNext": "Siguiente",
				"sPrevious": "Anterior"
			},
			"oAria": {
				"sSortAscending": ": Activar para ordenar la columna de manera ascendente",
				"sSortDescending": ": Activar para ordenar la columna de manera descendente"
			}
		},
		"sDom": "<'row-fluid'<'span12'f>r>t<'row-fluid'<'span12'p>>",
		"sPaginationType": "bootstrap"
	});

app/views/pedidos/show.html.haml
- content_for :title, @pedido ? "Pedido ##{@pedido.id}" : "Pedidos"
.NotaEntrega
	.hero-unit	
		%h2		
			%center
				=	"Pedido ##{@pedido.id}"
	.well
		%p
			=link_to "<i class='icon-file'> Nota de Entrega</i>".html_safe, pedido_path(@pedido, :format=>'pdf'), class: 'btn', :'data-skip-pjax' => true, :target => '_blank'
	%hr
	.page-header
		%h4
			%center
				Datos del Personal
	%br
	.row#DatosPersonales
		.span4
			%ul
				%li
					%b
						Cedula:
					= @pedido.empleado.cedula
				%li
					%b
						Empleado:
					= "#{@pedido.empleado.nombre} #{@pedido.empleado.apellido}"
		.span4
			%ul
				%li
					%b
						Cargo:
					= @pedido.empleado.cargo
				%li
					%b
						Obra:
					= @pedido.obra.nombre
		.span4
			%ul
				%li
					%b
						Estado:
					= @pedido.estado
				%li
					%b
						Fecha:
					=@pedido.created_at.strftime("%d %b. %Y")
	%hr
	.page-header
		%h4
			%center
				Listado de Artículos
		%hr
			.row#TablaShow
				%table.table.table-bordered
					%thead
						%tr
							%th Codigo
							%th Nombre de Articulo
							%th Cantidad
							%th Cantidad Devuelta
							%th Unidad de Medida
							%th Estado

					%tbody
						- @pedido.articulos.each do |articulo|
							%tr
								%th
									=articulo.codigo
								%th
									=articulo.nombre
								%th
									= @pedido.cantidad_del_articulo_pedido(articulo.id)
								%th
									= @pedido.cantidad_devuelta_del_articulo_pedido(articulo.id)
								%th
									=articulo.unidad_de_medida
								- if @pedido.estado_del_articulo_pedido(articulo.id) == "Activo"
									%th{:style=>"background: #82FA58;"}
										= @pedido.estado_del_articulo_pedido(articulo.id)
								- else
									%th{:style=>"background: #FA5858;"}
										= @pedido.estado_del_articulo_pedido(articulo.id)

	%br
.modal-footer	
	