config/routes.rb
Invinyx::Application.routes.draw do
  get "obra/index"

  get "proveedors/index"

  get "factura/index"

  resources :productos
  resources :pedidos do
    resources :devolucions, only: [:new]
    member do
      get :devoluciones
    end
  end
  resources :articulos
  resources :facturas
  resources :proveedors
  resources :devolucions
  resources :obras

  get "/agregar/empleado/:id" => 'pedidos#asignar_empleado_a_pedido', :as => :empleado_info 

  get "/agregar/articulo/:id" => 'pedidos#asignar_articulo_a_pedido', :as => :articulo_info
  
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users

  get '/agregar/:id' => 'application#articulos_facturas',  :as => :articulos_facturas

  

  root :to => 'articulos#index'

  match ':controller(/:action(/:id))(.:format)'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= content_for?(:title) ? content_for(:title) : "Invinyx" %> - Invinyx</title>
  <%= stylesheet_link_tag  "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%- if current_user %>
    <%=render :template => 'layouts/navbar' %>
    <div class='content'>   
    <section class='caja2'>
      <div data-pjax-container>
        <%= render :template => 'layouts/body_page' %>
      </div>
    </section>
    <footer class='footerU'><center>Performed by Inyxtech | All Right Reserve 2013</center></footer>
  <%- else %>
    <header>
      <section class='caja1'>       
        <div class='tituloApp'>  
          <h1>Invinyx<span style="color: #FFBF00;"><b>.</b></span></h1>
          <p>Sistema de Control de Inventarios.</p>
        </div>        
        <div class='logoInyx'><%= image_tag 'inyxlogo.png'%></div>
      </section>
    </header>    
    <div class='content'>   
        <div data-pjax-container>
          <%= render :template => 'layouts/body_page' %>
        </div>
      <footer class='footerLogin'><center>Performed by Inyxtech | All Right Reserve 2013</center></footer>
  <% end -%>
</div>
</body>
</html>

app/views/layouts/body_page.html.haml
- if current_user
	%ul.nav.nav-tabs
		%li.active#articulos-tab
			= link_to '<i class="icon-th-list"> Articulos</i>'.html_safe, "#{articulos_path}"
		%li#pedidos-tab
			= link_to '<i class="icon-shopping-cart"> Pedidos / <i class="icon-random"></i> Devoluciones</i>'.html_safe, pedidos_path
		%li#facturas-tab
			= link_to '<i class="icon-list-alt"> Facturas</i>'.html_safe, facturas_path
		%li#obras-tab
			= link_to '<i class="icon-briefcase"> Obras</i>'.html_safe, obras_path
		%li#proveedors-tab
			= link_to '<i class="icon-book"> Proveedores</i>'.html_safe, proveedors_path
=yield

:javascript
	$('.nav.nav-tabs li.active').removeClass('active');
	var x = "#"+window.location.href.split("/")[3]+"-tab"
	$(x).addClass('active');
	

app/views/layouts/navbar.html.haml
.navbar.navbar-inverse.navbar-fixed-top
	.navbar-inner
		.container-fluid
			%a.brand{:href=>'/'}
				= image_tag 'inyx.png', :size => "23x23", :style =>'margin-top:-3px;margin-top:-3px;'
				%span{:style => "font-size:18px;margin-left:-2;"}
					Inyxtech
				%span{:style => "color: #FFBF00;margin-left:-3px;"}
					%b .
			%ul.nav.pull-right
				-if current_user
					%li
						= link_to "<i class='icon-cog'></i> Administración".html_safe, rails_admin_path, :'data-skip-pjax' => true
				%li
					= link_to "<i class='icon-user'></i> #{current_user.nombre} #{current_user.apellido} ".html_safe, user_session_path
				%li
					= link_to '<span class="label label-important"><i class="icon-off"></i> Salir</span>'.html_safe, destroy_user_session_path, method: :delete
				- if current_user.respond_to?(:email) && current_user.email.present?
					%li= image_tag "#{(request.ssl? ? 'https://secure' : 'http://www')}.gravatar.com/avatar/#{Digest::MD5.hexdigest current_user.email}?s=30", :style => 'padding-top:5px'